language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: sr2oQY1fOGNQRslNyNLq8B6bVGrvkwIxf23mcYY7F87DPLVvJ799VE1yxKwOJQeVmcFXDwWnxo3pzLvhSYNS3yDHjt9ymJ0+togNx4TUKPPcOHzlTNr+CfTkcx684aypykJjfAgGxUQs5cF2BVutEvKGbCla8OuO+N42Kc8350w=
  on:
    tags: true
    repo: nipy/nitime
python:
- 2.7
- 3.5
env:
- CONDA_DEPS="pip pytest pytest-cov coverage numpy cython scipy matplotlib networkx" PIP_DEPS="coveralls python-coveralls nibabel"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- command -v conda >/dev/null || { wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS
install:
- python setup.py install
script:
  - py.test --pyargs nitime --cov-report term-missing --cov=nitime --verbose
after_success:
- coveralls
